import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";
import type { AiCopilotResponse, AiProviderStatus, DeveloperStorageReport, DuplicateGroup, DuplicateProgress, FileEntry, FileInspectionResult, FileInspectorMatch, Recommendation, RescuePlan, ScanProgress, ScanSummary, TimelineResponse, TimelineStatus, TreeNode } from "../types";
export const selectFolder = () => invoke<string|null>("select_folder");
export const selectInspectorFile = () => invoke<string|null>("select_inspector_file");
export const scan = (path:string,retentionDays:number) => invoke<ScanSummary>("scan_folder", { path, retentionDays });
export const cancel = () => invoke("cancel_scan");
export const duplicates = () => invoke<DuplicateGroup[]>("find_duplicates");
export const cancelDuplicates = () => invoke("cancel_duplicates");
export const recommendations = () => invoke<Recommendation[]>("get_recommendations");
export const deleteToTrash = (paths:string[]) => invoke<{deleted:string[]; errors:string[]; warnings:string[]}>("move_to_trash", { paths });
export const onProgress = (handler:(p:ScanProgress)=>void) => listen<ScanProgress>("scan-progress", e=>handler(e.payload));
export const onDuplicateProgress = (handler:(p:DuplicateProgress)=>void) => listen<DuplicateProgress>("duplicate-progress", e=>handler(e.payload));
export const onTimelineStatus = (handler:(status:TimelineStatus)=>void) => listen<TimelineStatus>("timeline-status", e=>handler(e.payload));
export const getFiles = (minimumBytes:number) => invoke<FileEntry[]>("get_files", { minimumBytes });
export const getTreeChildren = (path:string) => invoke<TreeNode[]>("get_tree_children", { path });
export const buildRescuePlan = (targetBytes:number) => invoke<RescuePlan>("build_rescue_plan", { targetBytes });
export const getTimeline = (rangeDays:number) => invoke<TimelineResponse>("get_timeline", { rangeDays });
export const getDeveloperStorage = () => invoke<DeveloperStorageReport>("get_developer_storage");
export const askAiCopilot = (question:string,providerId:string,model:string) => invoke<AiCopilotResponse>("ask_ai_copilot",{question,providerId,model});
export const cancelAiCopilot = () => invoke("cancel_ai_copilot");
export const findInspectorFileMatches = (query:string) => invoke<FileInspectorMatch[]>("find_inspector_file_matches",{query});
export const inspectFileContents = (path:string,allowOutsideScope:boolean) => invoke<FileInspectionResult>("inspect_file_contents",{path,allowOutsideScope});
export const aiProviderStatus = (providerId:string,model:string) => invoke<AiProviderStatus>("ai_provider_status",{providerId,model});
export const saveAiProviderKey = (providerId:string,apiKey:string) => invoke("save_ai_provider_key",{providerId,apiKey});
export const deleteAiProviderKey = (providerId:string) => invoke("delete_ai_provider_key",{providerId});
export const testAiProvider = (providerId:string,model:string) => invoke("test_ai_provider",{providerId,model});
