use crate::models::*;
use std::{
    collections::{HashMap, HashSet},
    path::Path,
};

const GIB: u64 = 1024 * 1024 * 1024;

#[derive(Clone)]
struct Candidate {
    path: String,
    category: &'static str,
    subtype: &'static str,
    confidence: DeveloperConfidence,
    risk: DeveloperRisk,
    priority: u8,
    reviewable: bool,
    source: &'static str,
}

fn norm(path: &str) -> String {
    path.replace('/', "\\")
        .trim_end_matches('\\')
        .to_ascii_lowercase()
}
fn base(path: &str) -> String {
    Path::new(path)
        .file_name()
        .unwrap_or_default()
        .to_string_lossy()
        .to_ascii_lowercase()
}
fn parent(path: &str) -> String {
    Path::new(path)
        .parent()
        .map(|p| norm(&p.to_string_lossy()))
        .unwrap_or_default()
}
fn marker(files: &HashSet<String>, dir: &str, names: &[&str]) -> bool {
    names
        .iter()
        .any(|n| files.contains(&format!("{dir}\\{}", n.to_ascii_lowercase())))
}

fn candidate(
    path: String,
    category: &'static str,
    subtype: &'static str,
    confidence: DeveloperConfidence,
    risk: DeveloperRisk,
    priority: u8,
    reviewable: bool,
    source: &'static str,
) -> Candidate {
    Candidate {
        path,
        category,
        subtype,
        confidence,
        risk,
        priority,
        reviewable,
        source,
    }
}

fn explanation(category: &str) -> (String, String) {
    match category {
        "NODE_DEPENDENCIES" => ("Installed JavaScript project dependencies. Modern projects can contain tens of thousands of dependency files. Removing them can break the project until dependencies are installed again.".into(), "Review the project manifest and lockfile before recreating dependencies with its package manager.".into()),
        "PYTHON_ENVIRONMENT"|"CONDA_ENVIRONMENT" => ("A project-specific Python environment containing an interpreter and installed packages. ML environments can be several GB. Removing it can break the project until it is recreated.".into(), "Confirm the project has sufficient environment or dependency metadata before removing anything.".into()),
        "RUST_BUILD" => ("Rust compiled build artifacts associated with a Cargo project. They can usually be regenerated by Cargo.".into(), "Review this project and remove artifacts only through the project's normal workflow.".into()),
        "JAVA_BUILD"|"DOTNET_BUILD"|"WEB_BUILD"|"BUILD_ARTIFACT" => ("Generated project build output identified using nearby project metadata. Removing it may require a rebuild.".into(), "Review the owning project before removing generated output.".into()),
        "PACKAGE_CACHE"|"IDE_CACHE" => ("A recognized development-tool cache. Cached data may be downloaded or generated again and can affect offline work.".into(), "Use the owning tool's supported cache-management workflow.".into()),
        "AI_MODEL"|"AI_MODEL_CACHE" => ("Local AI/ML model storage. Models can be several GB and removing one may require the associated application to download it again.".into(), "Confirm which application and model uses this location before making changes.".into()),
        "DOCKER_STORAGE" => ("Storage belonging to Docker/container infrastructure. It may contain images, layers, volumes, or application data.".into(), "Do not manually delete internal files; use Docker Desktop's supported management interface.".into()),
        "WSL_STORAGE"|"VM_STORAGE" => ("A virtual disk that may contain an entire operating system and user data.".into(), "Do not delete it directly; review it through the owning WSL or virtual-machine application.".into()),
        _ => ("Storage produced or maintained by a recognized development tool.".into(), "Review the owning tool or project before making changes.".into()),
    }
}

pub fn analyze(
    files: &[FileEntry],
    directories: &HashMap<String, FileEntry>,
) -> DeveloperStorageReport {
    analyze_cancellable(files, directories, &|| false).expect("uncancelled analysis")
}

pub fn analyze_cancellable(
    files: &[FileEntry],
    directories: &HashMap<String, FileEntry>,
    cancelled: &dyn Fn() -> bool,
) -> Result<DeveloperStorageReport, String> {
    let check = || {
        if cancelled() {
            Err("Timeline cancelled; completed scan remains available.".to_string())
        } else {
            Ok(())
        }
    };
    check()?;
    let file_paths: HashSet<String> = files.iter().map(|f| norm(&f.path)).collect();
    let dotnet_parents: HashSet<String> = files
        .iter()
        .filter(|f| {
            matches!(
                f.extension.to_ascii_lowercase().as_str(),
                "csproj" | "fsproj" | "vbproj" | "sln"
            )
        })
        .map(|f| parent(&f.path))
        .collect();
    let mut candidates = Vec::new();
    for d in directories.values().filter(|d| d.size > 0) {
        check()?;
        let p = norm(&d.path);
        let n = base(&d.path);
        let par = parent(&d.path);
        let cargo = marker(&file_paths, &par, &["cargo.toml"]);
        let node = marker(&file_paths, &par, &["package.json"]);
        let maven = marker(&file_paths, &par, &["pom.xml"]);
        let gradle = marker(
            &file_paths,
            &par,
            &["build.gradle", "build.gradle.kts", "settings.gradle"],
        );
        let dotnet = dotnet_parents.contains(&par);
        let python_marker = marker(&file_paths, &p, &["pyvenv.cfg"]);
        let lower = p.as_str();
        let c = if n == "node_modules" && node {
            Some(candidate(
                p,
                "NODE_DEPENDENCIES",
                "Project dependencies",
                DeveloperConfidence::High,
                DeveloperRisk::ReviewRequired,
                80,
                true,
                "node_modules plus package.json",
            ))
        } else if n == "node_modules" {
            Some(candidate(
                p,
                "NODE_DEPENDENCIES",
                "Project dependencies",
                DeveloperConfidence::Medium,
                DeveloperRisk::ReviewRequired,
                70,
                true,
                "node_modules convention",
            ))
        } else if (n == ".venv" || n == "venv") && python_marker {
            Some(candidate(
                p,
                "PYTHON_ENVIRONMENT",
                "Python virtual environment",
                DeveloperConfidence::High,
                DeveloperRisk::ReviewRequired,
                80,
                true,
                "venv name plus pyvenv.cfg",
            ))
        } else if n == "target" && cargo {
            Some(candidate(
                p,
                "RUST_BUILD",
                "Cargo target",
                DeveloperConfidence::High,
                DeveloperRisk::ReviewRequired,
                80,
                true,
                "target plus Cargo.toml",
            ))
        } else if n == "target" && maven {
            Some(candidate(
                p,
                "JAVA_BUILD",
                "Maven target",
                DeveloperConfidence::High,
                DeveloperRisk::ReviewRequired,
                80,
                true,
                "target plus pom.xml",
            ))
        } else if n == "build" && gradle {
            Some(candidate(
                p,
                "JAVA_BUILD",
                "Gradle build output",
                DeveloperConfidence::High,
                DeveloperRisk::ReviewRequired,
                80,
                true,
                "build plus Gradle project metadata",
            ))
        } else if (n == "bin" || n == "obj") && dotnet {
            Some(candidate(
                p,
                "DOTNET_BUILD",
                ".NET build output",
                DeveloperConfidence::High,
                DeveloperRisk::ReviewRequired,
                80,
                true,
                "bin/obj plus .NET project metadata",
            ))
        } else if (n == "dist" || n == "build" || n == ".next") && node {
            Some(candidate(
                p,
                "WEB_BUILD",
                "Web build output",
                DeveloperConfidence::High,
                DeveloperRisk::ReviewRequired,
                75,
                true,
                "generated directory plus package.json",
            ))
        } else if lower.contains("\\.cache\\huggingface") || lower.ends_with("\\huggingface\\hub") {
            Some(candidate(
                p,
                "AI_MODEL_CACHE",
                "Hugging Face cache",
                DeveloperConfidence::High,
                DeveloperRisk::ReviewRequired,
                100,
                true,
                "known Hugging Face cache path",
            ))
        } else if lower.contains("\\.ollama\\models") {
            Some(candidate(
                p,
                "AI_MODEL_CACHE",
                "Ollama models",
                DeveloperConfidence::High,
                DeveloperRisk::ReviewRequired,
                100,
                true,
                "known Ollama model path",
            ))
        } else if lower.contains("\\docker\\")
            && (n == "data" || n == "wsl" || n == "docker-desktop-data")
        {
            Some(candidate(
                p,
                "DOCKER_STORAGE",
                "Docker managed storage",
                DeveloperConfidence::High,
                DeveloperRisk::HighManagedExternally,
                110,
                false,
                "known Docker application-data convention",
            ))
        } else if lower.ends_with("\\.gradle\\caches") {
            Some(candidate(
                p,
                "PACKAGE_CACHE",
                "Gradle cache",
                DeveloperConfidence::High,
                DeveloperRisk::ReviewRequired,
                90,
                true,
                "known Gradle cache path",
            ))
        } else if lower.ends_with("\\.cache\\pip") || lower.ends_with("\\pip\\cache") {
            Some(candidate(
                p,
                "PACKAGE_CACHE",
                "Python package cache",
                DeveloperConfidence::High,
                DeveloperRisk::ReviewRequired,
                90,
                true,
                "known pip cache path",
            ))
        } else if lower.ends_with("\\npm-cache")
            || lower.ends_with("\\.npm")
            || lower.ends_with("\\yarn\\cache")
            || lower.ends_with("\\pnpm\\store")
        {
            Some(candidate(
                p,
                "PACKAGE_CACHE",
                "JavaScript package cache",
                DeveloperConfidence::High,
                DeveloperRisk::ReviewRequired,
                90,
                true,
                "known package-manager cache path",
            ))
        } else if n == "pkgs" && lower.contains("\\conda") {
            Some(candidate(
                p,
                "PACKAGE_CACHE",
                "Conda package cache",
                DeveloperConfidence::High,
                DeveloperRisk::ReviewRequired,
                90,
                true,
                "known Conda package-cache path",
            ))
        } else if n == "envs" && lower.contains("\\conda") {
            Some(candidate(
                p,
                "CONDA_ENVIRONMENT",
                "Conda environments",
                DeveloperConfidence::High,
                DeveloperRisk::ReviewRequired,
                85,
                true,
                "known Conda environments path",
            ))
        } else {
            None
        };
        if let Some(x) = c {
            candidates.push(x);
        }
    }
    for f in files {
        check()?;
        let ext = f.extension.to_ascii_lowercase();
        let p = norm(&f.path);
        let c = if matches!(
            ext.as_str(),
            "gguf" | "safetensors" | "onnx" | "pt" | "pth" | "ckpt"
        ) {
            Some(candidate(
                p,
                "AI_MODEL",
                "Standalone model file",
                DeveloperConfidence::High,
                DeveloperRisk::ReviewRequired,
                60,
                true,
                "recognized model-file extension",
            ))
        } else if matches!(ext.as_str(), "vhd" | "vhdx" | "vmdk") {
            let docker = p.contains("\\docker\\");
            let category = if docker {
                "DOCKER_STORAGE"
            } else if p.contains("\\wsl\\") {
                "WSL_STORAGE"
            } else {
                "VM_STORAGE"
            };
            Some(candidate(
                p,
                category,
                "Virtual disk",
                DeveloperConfidence::High,
                DeveloperRisk::HighManagedExternally,
                105,
                false,
                "recognized virtual-disk extension",
            ))
        } else {
            None
        };
        if let Some(x) = c {
            candidates.push(x)
        }
    }
    candidates.sort_by(|a, b| {
        a.path
            .cmp(&b.path)
            .then_with(|| b.priority.cmp(&a.priority))
    });
    let mut owned: Vec<Candidate> = Vec::new();
    let mut owned_paths = HashSet::new();
    for c in candidates {
        check()?;
        // Lexical order visits each ancestor before its descendants. Preserve
        // outermost ownership without comparing every candidate to every owner.
        let mut ancestor = c.path.as_str();
        let mut covered = owned_paths.contains(ancestor);
        while !covered {
            let Some((next, _)) = ancestor.rsplit_once('\\') else {
                break;
            };
            covered = owned_paths.contains(next);
            ancestor = next;
        }
        if !covered {
            owned_paths.insert(c.path.clone());
            owned.push(c);
        }
    }
    let by_file: HashMap<String, &FileEntry> = files.iter().map(|f| (norm(&f.path), f)).collect();
    let by_directory: HashMap<String, &FileEntry> =
        directories.values().map(|d| (norm(&d.path), d)).collect();
    // Index descendant counts once, instead of scanning all files for every finding.
    let mut counts: HashMap<String, u64> = HashMap::new();
    for path in by_file.keys() {
        check()?;
        let mut ancestor = path.as_str();
        while let Some((next, _)) = ancestor.rsplit_once('\\') {
            *counts.entry(next.to_owned()).or_default() += 1;
            ancestor = next;
        }
    }
    let mut findings = Vec::new();
    for c in owned {
        check()?;
        let directory = by_directory.get(&c.path).copied();
        let file = by_file.get(&c.path).copied();
        let size = directory
            .map(|d| d.size)
            .or_else(|| file.map(|f| f.size))
            .unwrap_or(0);
        if size == 0 {
            continue;
        }
        let count = if directory.is_some() {
            counts.get(&c.path).copied().unwrap_or(0)
        } else {
            1
        };
        let (why, action) = explanation(c.category);
        let name = directory
            .map(|d| d.name.clone())
            .or_else(|| file.map(|f| f.name.clone()))
            .unwrap_or_else(|| c.path.clone());
        let modified = directory
            .and_then(|d| d.modified.clone())
            .or_else(|| file.and_then(|f| f.modified.clone()));
        findings.push(DeveloperStorageFinding {
            id: format!("{}:{}", c.category, c.path),
            category: c.category.into(),
            subtype: c.subtype.into(),
            path: c.path,
            name,
            size_bytes: size,
            item_count: count,
            modified,
            confidence: c.confidence,
            risk: c.risk,
            explanation: why,
            review_action: action,
            source: c.source.into(),
            reviewable: c.reviewable,
        });
    }
    findings.sort_by(|a, b| b.size_bytes.cmp(&a.size_bytes));
    let total_bytes = findings
        .iter()
        .fold(0u64, |n, f| n.saturating_add(f.size_bytes));
    let potential_review_bytes = findings
        .iter()
        .filter(|f| f.reviewable)
        .fold(0u64, |n, f| n.saturating_add(f.size_bytes));
    let mut sums: HashMap<String, (u64, u64)> = HashMap::new();
    for f in &findings {
        let e = sums.entry(f.category.clone()).or_default();
        e.0 = e.0.saturating_add(f.size_bytes);
        e.1 += 1
    }
    let mut categories: Vec<_> = sums
        .into_iter()
        .map(
            |(category, (size_bytes, finding_count))| DeveloperCategoryTotal {
                category,
                size_bytes,
                finding_count,
            },
        )
        .collect();
    categories.sort_by(|a, b| b.size_bytes.cmp(&a.size_bytes));
    let lead = categories
        .iter()
        .take(3)
        .map(|c| {
            format!(
                "{} ({:.1} GB)",
                c.category.replace('_', " "),
                c.size_bytes as f64 / GIB as f64
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    let summary = if total_bytes == 0 {
        "No confidently identifiable developer storage was found in this scan.".into()
    } else {
        format!("Developer-related files consume approximately {:.1} GB of this scan. The largest categories are {}. SpacePilot identified approximately {:.1} GB worth reviewing; this does not mean it can all be safely removed.",total_bytes as f64/GIB as f64,lead,potential_review_bytes as f64/GIB as f64)
    };
    Ok(DeveloperStorageReport{total_bytes,potential_review_bytes,findings,categories,summary,warnings:vec!["Classifications use path and scan metadata only. SpacePilot did not read source-code or file contents.".into()]})
}

#[cfg(test)]
mod tests {
    #[test]
    fn cancellation_during_analysis_is_observed() {
        let files: Vec<_> = (0..4000)
            .map(|i| f(&format!("C:\\scan\\p\\node_modules\\f{i}.bin"), 1))
            .collect();
        let dirs = HashMap::from([(
            "C:\\scan\\p\\node_modules".into(),
            d("C:\\scan\\p\\node_modules", 4000),
        )]);
        let checks = std::cell::Cell::new(0);
        let start = std::time::Instant::now();
        let result = analyze_cancellable(&files, &dirs, &|| {
            checks.set(checks.get() + 1);
            checks.get() > 50
        });
        assert!(result.is_err());
        eprintln!(
            "analysis_cancel elapsed_ms={:.3} checkpoints={}",
            start.elapsed().as_secs_f64() * 1000.0,
            checks.get()
        );
    }

    #[test]
    fn indexed_counts_and_marker_scope_are_exact() {
        let files = vec![
            f("C:\\p\\ONE.CSPROJ", 1),
            f("C:\\p\\bin\\a.dll", 10),
            f("C:\\p\\bin\\nested\\b.dll", 20),
            f("C:\\p\\binary\\c.bin", 40),
            f("C:\\q\\bin\\d.dll", 30),
        ];
        let report = run(
            files,
            vec![
                d("C:\\p\\bin", 30),
                d("C:\\p\\bin\\nested", 20),
                d("C:\\q\\bin", 30),
            ],
        );
        let finding = report
            .findings
            .iter()
            .find(|f| f.path == "c:\\p\\bin")
            .unwrap();
        assert_eq!(finding.item_count, 2);
        assert_eq!(finding.size_bytes, 30);
        assert_eq!(finding.category, "DOTNET_BUILD");
        assert!(!report.findings.iter().any(|f| f.path == "c:\\q\\bin"));
    }
    #[test]
    #[ignore = "explicit comparison with the previous quadratic marker search"]
    fn marker_search_before_after() {
        let files: Vec<_> = (0..10_000)
            .map(|i| f(&format!("C:\\scan\\p{}\\f{i}.bin", i % 100), 1))
            .collect();
        let start = std::time::Instant::now();
        for i in 0..100 {
            let par = format!("c:\\scan\\p{i}");
            assert!(!files.iter().any(|f| parent(&f.path) == par
                && matches!(
                    f.extension.to_ascii_lowercase().as_str(),
                    "csproj" | "fsproj" | "vbproj" | "sln"
                )));
        }
        let before = start.elapsed();
        let start = std::time::Instant::now();
        let parents: HashSet<_> = files
            .iter()
            .filter(|f| {
                matches!(
                    f.extension.to_ascii_lowercase().as_str(),
                    "csproj" | "fsproj" | "vbproj" | "sln"
                )
            })
            .map(|f| parent(&f.path))
            .collect();
        for i in 0..100 {
            assert!(!parents.contains(&format!("c:\\scan\\p{i}")));
        }
        eprintln!(
            "marker benchmark N=10000 D=100 before_ms={:.3} after_ms={:.3}",
            before.as_secs_f64() * 1000.0,
            start.elapsed().as_secs_f64() * 1000.0
        );
    }
    use super::*;
    fn f(path: &str, size: u64) -> FileEntry {
        FileEntry {
            path: path.into(),
            name: base(path),
            extension: Path::new(path)
                .extension()
                .unwrap_or_default()
                .to_string_lossy()
                .into(),
            size,
            modified: None,
            category: "Other".into(),
            is_directory: false,
        }
    }
    fn d(path: &str, size: u64) -> FileEntry {
        FileEntry {
            is_directory: true,
            ..f(path, size)
        }
    }
    fn run(fs: Vec<FileEntry>, ds: Vec<FileEntry>) -> DeveloperStorageReport {
        analyze(&fs, &ds.into_iter().map(|d| (d.path.clone(), d)).collect())
    }
    #[test]
    fn detects_node_modules_with_manifest() {
        let r = run(
            vec![
                f("C:\\p\\package.json", 1),
                f("C:\\p\\node_modules\\a.js", 9),
            ],
            vec![d("C:\\p\\node_modules", 9)],
        );
        assert_eq!(r.findings[0].category, "NODE_DEPENDENCIES");
        assert_eq!(r.findings[0].confidence, DeveloperConfidence::High)
    }
    #[test]
    fn rejects_node_modules_like_name() {
        assert_eq!(
            run(vec![], vec![d("C:\\p\\node_modules_backup", 9)]).total_bytes,
            0
        )
    }
    #[test]
    fn venv_requires_marker() {
        assert_eq!(
            run(vec![], vec![d("C:\\p\\env", 9), d("C:\\p\\venv", 9)]).total_bytes,
            0
        );
        assert_eq!(
            run(
                vec![f("C:\\p\\.venv\\pyvenv.cfg", 1)],
                vec![d("C:\\p\\.venv", 9)]
            )
            .findings[0]
                .category,
            "PYTHON_ENVIRONMENT"
        )
    }
    #[test]
    fn rust_and_generic_target() {
        assert_eq!(run(vec![], vec![d("C:\\p\\target", 9)]).total_bytes, 0);
        assert_eq!(
            run(vec![f("C:\\p\\Cargo.toml", 1)], vec![d("C:\\p\\target", 9)]).findings[0].category,
            "RUST_BUILD"
        )
    }
    #[test]
    fn contextual_builds() {
        for (files, dir, cat) in [
            (
                vec![f("C:\\p\\pom.xml", 1)],
                d("C:\\p\\target", 9),
                "JAVA_BUILD",
            ),
            (
                vec![f("C:\\p\\x.csproj", 1)],
                d("C:\\p\\obj", 9),
                "DOTNET_BUILD",
            ),
            (
                vec![f("C:\\p\\package.json", 1)],
                d("C:\\p\\dist", 9),
                "WEB_BUILD",
            ),
        ] {
            assert_eq!(run(files, vec![dir]).findings[0].category, cat)
        }
    }
    #[test]
    fn models_and_bin_safety() {
        let r = run(
            vec![
                f("C:\\m\\a.gguf", 10),
                f("C:\\m\\b.safetensors", 11),
                f("C:\\m\\x.bin", 99),
            ],
            vec![],
        );
        assert_eq!(r.total_bytes, 21);
        assert_eq!(r.findings.len(), 2)
    }
    #[test]
    fn known_model_caches_and_nested_ownership() {
        let r = run(
            vec![f("C:\\u\\.cache\\huggingface\\a.gguf", 10)],
            vec![d("C:\\u\\.cache\\huggingface", 10)],
        );
        assert_eq!(r.total_bytes, 10);
        assert_eq!(r.findings.len(), 1);
        assert_eq!(r.findings[0].category, "AI_MODEL_CACHE")
    }
    #[test]
    fn docker_and_vm_are_not_reviewable() {
        let r = run(
            vec![
                f("C:\\Docker\\data\\disk.vhdx", 10),
                f("C:\\vm\\x.vmdk", 20),
            ],
            vec![],
        );
        assert_eq!(r.total_bytes, 30);
        assert_eq!(r.potential_review_bytes, 0);
        assert!(r.findings.iter().all(|f| !f.reviewable))
    }
    #[test]
    fn nested_dependencies_count_once_and_saturate() {
        let r = run(
            vec![
                f("C:\\p\\package.json", 1),
                f("C:\\p\\node_modules\\x\\a", u64::MAX),
            ],
            vec![
                d("C:\\p\\node_modules", u64::MAX),
                d("C:\\p\\node_modules\\x", u64::MAX),
            ],
        );
        assert_eq!(r.total_bytes, u64::MAX)
    }
    #[test]
    fn no_storage_and_mixed_scan() {
        assert_eq!(run(vec![f("C:\\photos\\a.jpg", 2)], vec![]).total_bytes, 0);
        let r = run(
            vec![f("C:\\p\\Cargo.toml", 1), f("C:\\m\\x.onnx", 7)],
            vec![d("C:\\p\\target", 5)],
        );
        assert_eq!(r.total_bytes, 12);
        assert_eq!(r.categories.len(), 2)
    }
}
