"""billing lifecycle and password reset

Revision ID: e99aa55c49a9
Revises: 962df0715c67
Create Date: 2026-09-15 23:30:23.096103

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e99aa55c49a9"
down_revision: Union[str, None] = "962df0715c67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("provider_event_id", sa.String(length=160), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("processing_status", sa.String(length=24), nullable=False),
        sa.Column("safe_error", sa.String(length=240), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_events_provider_event_id"),
        "payment_events",
        ["provider_event_id"],
        unique=True,
    )
    op.create_table(
        "password_resets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_password_resets_user_id"), "password_resets", ["user_id"], unique=False
    )
    op.add_column(
        "subscription_records",
        sa.Column("provider_customer_id", sa.String(length=160), nullable=True),
    )
    op.add_column(
        "subscription_records",
        sa.Column(
            "internal_plan",
            sa.String(length=24),
            nullable=False,
            server_default="PRO_MONTHLY",
        ),
    )
    op.add_column(
        "subscription_records",
        sa.Column("provider_price_id", sa.String(length=160), nullable=True),
    )
    op.add_column(
        "subscription_records",
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "subscription_records",
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "subscription_records",
        sa.Column(
            "cancel_at_period_end",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column(
        "subscription_records",
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "subscription_records",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.create_index(
        op.f("ix_subscription_records_provider_customer_id"),
        "subscription_records",
        ["provider_customer_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_subscription_records_external_id", "subscription_records", ["external_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_subscription_records_external_id", "subscription_records", type_="unique"
    )
    op.drop_index(
        op.f("ix_subscription_records_provider_customer_id"),
        table_name="subscription_records",
    )
    op.drop_column("subscription_records", "updated_at")
    op.drop_column("subscription_records", "canceled_at")
    op.drop_column("subscription_records", "cancel_at_period_end")
    op.drop_column("subscription_records", "current_period_end")
    op.drop_column("subscription_records", "current_period_start")
    op.drop_column("subscription_records", "provider_price_id")
    op.drop_column("subscription_records", "internal_plan")
    op.drop_column("subscription_records", "provider_customer_id")
    op.drop_index(op.f("ix_password_resets_user_id"), table_name="password_resets")
    op.drop_table("password_resets")
    op.drop_index(
        op.f("ix_payment_events_provider_event_id"), table_name="payment_events"
    )
    op.drop_table("payment_events")
    # ### end Alembic commands ###
